# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/android:api-28

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/CircleCI-Android

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m # limit the maximum heap size to prevent out of memory errors
      TERM: dumb # Use dumb terminal to avoid weird output from Gradle.

    steps:
      - checkout

      - restore_cache:
          name: Restore Cache
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          name: Save Cache
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
          
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      
      - run:
          name: Run Unit Tests
          command: ./gradlew test 

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
      
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
     
      - run:
          name: Run Instrumented Tests
          command: ./gradlew connectedAndroidTest
